<?php

namespace AppBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find Episode who will be released in future
     * @return array
     */
    public function findEpisodeInComing() {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT e
             FROM AppBundle:Episode e
             WHERE e.date >= CURRENT_DATE()
             ORDER BY e.date ASC'
        );

        return $query->getResult();
    }
}
